## **전동킥보드 견인 현황 데이터셋 전처리**

- 2021-07 ~ 2025-12 까지의 서울시 전동킥보드 견인 현황 종합
  
- 각각의 데이터셋의 구성을 파악하고, 형식에 맞게 데이터셋 읽어오기
  
- 각각의 데이터프레임 전처리
  
- 추후 분석 과정에서 활용하기 위해 '신고일' 열의 파생변수 '신고월' 열 추가

- 처리한 데이터프레임들을 하나의 `df_merged`로 병합

- `df_merged` 데이터 점검, CSV 저장 (utf-8-sig)

#### **결과물: 서울특별시_전동킥보드_견인_현황_202107~202512.csv**

  #### **목표 데이터 설명**
  * **신고일** - 전동킥보드 견인 조치 신고일입니다.
  * **구정보** - 견인 조치 된 관련 자치구입니다(예: 은평구)
  * **주소** - 견인 조치 상세 주소입니다.
  * **유형** - 신고 유형입니다. 불편신고, 보도 중앙 등 다양한 유형이 존재합니다.
  * **조치일** - 실제 견인이 실시된 날짜입니다.
  * **신고월** - (추가) '신고일' 열에서 추출한 파생변수입니다.

In [64]:
import pandas as pd
import numpy as np

#### 필요 컬럼명 정의, 출력용 함수 정의

In [65]:
# 필요한 컬럼명 정의
cols=['신고일', '구정보', '주소', '유형', '조치일']

# 편의용 함수 정의
def my_display(df, num_rows=5):
    display(df.head(num_rows))
    display(df.tail(num_rows))
    print(df.dtypes)

## 데이터셋 불러오기

### 2021-07 ~ 2023-08 데이터셋 불러오기

In [66]:
# 2022031.csv, 20230131.csv, 20230831.csv 는 과거 데이터가 계속 누적되어 업데이트됨
# 2021년 7월부터 2023년 8월까지의 데이터는 20230831.csv에 누적되어 업데이트됨
df_20230831 = pd.read_csv('서울특별시_전동킥보드_견인_현황_20230831.csv', encoding='cp949', usecols=cols)

my_display(df_20230831, 3)

          신고일   구정보                      주소                  유형         조치일
0  2021-07-15  영등포구   서울특별시 영등포구 여의도동 84-10  보도와 차도가 구분된 도로의 차도  2021-07-15
1  2021-07-15  영등포구  서울특별시 영등포구 영등포동1가 97-4               보도 중앙  2021-07-15
2  2021-07-15   동작구    서울특별시 동작구 노량진동 231-2  보도와 차도가 구분된 도로의 차도  2021-07-15

               신고일   구정보                     주소        유형         조치일
123724  2023-08-31  동대문구  서울특별시 동대문구 전농동 150-56      불편신고  2023-08-31
123725  2023-08-31  동대문구  서울특별시 동대문구 전농동 584-21      불편신고  2023-08-31
123726  2023-08-31   관악구  서울특별시 관악구 봉천동 1529-47  빨리 가져가세요  2023-09-01

신고일    str
구정보    str
주소     str
유형     str
조치일    str
dtype: object

### 2023 하반기 데이터셋 불러오기

In [67]:
# 일부 월별 데이터 앞부분 스니펫에 빈 열이 콤마(,,,)로 나타나서, Pandas가 자동으로 열을 4개로 인식하는 경우가 있음.
# 이 경우, 불필요한 열을 제외하고 읽어와야 함.

In [68]:
# xlsx 파일 읽기 (read_excel 사용)
# 20231231.xlsx 파일은 이전과 달리 과거 데이터가 누적되지 않고, 매월 말일 기준으로 해당 월의 데이터만 업데이트됨
# header=1:         해당 파일 스니펫들은 첫 번째 행/열이 비어있고, 두 번째 행/열부터 실제 데이터가 시작되어 있음
# sheet_name=None:  엑셀 내 모든 시트를 딕셔너리 형태로 불러오기
all_sheets = pd.read_excel('서울특별시_전동킥보드_견인_현황_20231231.xlsx',
                            usecols=cols, header=1, sheet_name=None)

# 딕셔너리로 불러온 시트들을 하나의 데이터프레임으로 합치기
df_20231231 = pd.concat(all_sheets.values(), ignore_index=True)

my_display(df_20231231, 3)

         신고일  구정보                      주소              유형        조치일
0 2023-09-01  도봉구     서울특별시 도봉구 쌍문동 482-1  점자블록, 엘리베이터 입구 2023-09-01
1 2023-09-01  강동구       서울특별시 강동구 성내동 478   버스정류장, 택시 승강장 2023-09-01
2 2023-09-01  성동구  서울특별시 성동구 성수동2가 277-25     횡단보도, 산책로 등 2023-09-01

             신고일  구정보                   주소                  유형        조치일
22997 2023-12-29  종로구  서울특별시 종로구 가회동 1-255  보도와 차도가 구분된 도로의 차도 2023-12-29
22998 2023-12-29  종로구   서울특별시 종로구 사직동 1-38       버스정류장, 택시 승강장 2023-12-29
22999 2023-12-29  종로구   서울특별시 종로구 사직동 1-38       버스정류장, 택시 승강장 2023-12-29

신고일    datetime64[us]
구정보               str
주소                str
유형                str
조치일    datetime64[us]
dtype: object

### 2024 상반기 데이터셋 불러오기

In [83]:
# 이전과 같은 방식으로 읽어오기(첫 번째 행이 비어있으므로 header=1로 지정)
all_sheets = pd.read_excel('서울시 전동킥보드 견인 현황(24년 상반기).xlsx',
                            usecols=cols, header=1,sheet_name=None)

df_20240630 = pd.concat(all_sheets.values(), ignore_index=True)

my_display(df_20240630, 3)

         신고일  구정보                     주소              유형        조치일
0 2024-01-01  송파구  서울특별시 송파구 마천동 128-127  건물, 상가 보행자 진출입 2024-01-02
1 2024-01-01  송파구      서울특별시 송파구 거여동 604  건물, 상가 보행자 진출입 2024-01-02
2 2024-01-01  송파구      서울특별시 송파구 장지동 839          자전거 도로 2024-01-02

             신고일  구정보                    주소           유형        조치일
39038 2024-06-30  동작구  서울특별시 동작구 사당동 240-12       그 외 지역 2024-07-01
39039 2024-06-30  동작구  서울특별시 동작구 상도동 210-94       그 외 지역 2024-07-01
39040 2024-06-30  금천구   서울특별시 금천구 시흥동 939-3  횡단보도 주변(3m) 2024-07-01

신고일    datetime64[us]
구정보               str
주소                str
유형                str
조치일    datetime64[us]
dtype: object

### 2024 하반기 데이터셋 불러오기

In [70]:
all_sheets = pd.read_excel('서울특별시_전동킥보드_견인_현황(24.7~12월).xlsx',
                            usecols=cols, header=1,sheet_name=None)

df_20241231 = pd.concat(all_sheets.values(), ignore_index=True)

my_display(df_20241231, 3)

         신고일  구정보                   주소                  유형        조치일
0 2024-07-01  은평구  서울특별시 은평구 응암동 39-14         횡단보도 주변(3m) 2024-07-01
1 2024-07-01  은평구  서울특별시 은평구 녹번동 82-39    보호구역(어린이·노인·장애인) 2024-07-01
2 2024-07-01  송파구     서울특별시 송파구 가락동 62  보도와 차도가 구분된 도로의 차도 2024-07-01

             신고일   구정보                     주소                유형        조치일
50288 2024-12-31  서대문구  서울특별시 서대문구 북가좌동 352-1     지하철역 전면(5m이내) 2024-12-31
50289 2024-12-31  서대문구   서울특별시 서대문구 홍은동 202-5       횡단보도 주변(3m) 2024-12-31
50290 2024-12-31   은평구    서울특별시 은평구 구산동 224-3  보호구역(어린이·노인·장애인) 2024-12-31

신고일    datetime64[us]
구정보               str
주소                str
유형                str
조치일    datetime64[us]
dtype: object

### 2025 상반기 데이터셋 불러오기

In [71]:
all_sheets = pd.read_excel('서울특별시_전동킥보드_견인_현황(25.1~6월).xlsx',
                            usecols=cols, header=1,sheet_name=None)

df_20250630 = pd.concat(all_sheets.values(), ignore_index=True)

my_display(df_20250630, 3)

         신고일  구정보                   주소      유형        조치일
0 2025-01-02  송파구  서울특별시 송파구 문정동 205-9  자전거 도로 2025-01-02
1 2025-01-02  송파구  서울특별시 송파구 문정동 221-3  자전거 도로 2025-01-02
2 2025-01-02  송파구  서울특별시 송파구 문정동 221-3  자전거 도로 2025-01-02

             신고일   구정보                       주소           유형        조치일
31686 2025-06-30  영등포구    서울특별시 영등포구 도림동 184-32   상기 사항 외 보도 2025-06-30
31687 2025-06-30  영등포구  서울특별시 영등포구 영등포동 618-497   상기 사항 외 보도 2025-06-30
31688 2025-06-30   서초구       서울특별시 서초구 서초동 1378  횡단보도 주변(3m) 2025-06-30

신고일    datetime64[us]
구정보               str
주소                str
유형                str
조치일    datetime64[us]
dtype: object

### 2025 하반기 데이터셋 불러오기

In [72]:
all_sheets = pd.read_excel('서울특별시_전동킥보드_견인_현황(25.7~12월).xlsx',
                            usecols=cols, header=1,sheet_name=None)

df_20251231 = pd.concat(all_sheets.values(), ignore_index=True)

my_display(df_20251231, 3)

          신고일  구정보                    주소                  유형         조치일
0  2025-07-01  동작구     서울특별시 동작구 상도동 511  점자블록 또는 교통약자 엘리베이터  2025-07-02
1  2025-07-01  송파구   서울특별시 송파구 가락동 100-2          상기 사항 외 보도  2025-07-02
2  2025-07-01  서초구  서울특별시 서초구 양재동 402-17          상기 사항 외 보도  2025-07-01

              신고일   구정보                     주소                  유형         조치일
33042  2025-12-31   강서구     서울특별시 강서구 화곡동 1146  보도와 차도가 구분된 도로의 차도  2025-12-31
33043  2025-12-31   강서구     서울특별시 강서구 가양동 1484    보호구역(어린이·노인·장애인)  2025-12-31
33044  2025-12-31  서대문구  서울특별시 서대문구 남가좌동 293-3       지하철역 전면(5m이내)  2025-12-31

신고일    str
구정보    str
주소     str
유형     str
조치일    str
dtype: object

## 데이터셋 전처리

### 필요한 함수를 작성하여, 결측치, 데이터타입 등을 처리합니다.

In [73]:
# 데이터프레임의 결측치 조회 함수 정의
def check_missing_values(df, df_name):
    print(f"{df_name} 결측치 개수:")
    print(df.isnull().sum())

In [74]:
# 데이터 전처리 함수 정의
def preprocess_data(df):
    # 결측치가 존재하는 행 제거
    df = df.dropna(subset=['신고일', '구정보', '유형', '조치일'])

    # '신고일'과 '조치일'을 datetime 형식으로 변환
    df['신고일'] = pd.to_datetime(df['신고일'], errors='coerce')
    df['조치일'] = pd.to_datetime(df['조치일'], errors='coerce')
    
    # '구정보'에서 구 이름만 추출 (예: '강남구'에서 '강남구' 추출)
    df['구정보'] = df['구정보'].str.extract(r'(\w+구)')

    # 신고월 파생변수 생성
    df['신고월'] = df['신고일'].dt.to_period('M')
    
    return df

In [75]:
# 데이터 전처리
df_20230831 = preprocess_data(df_20230831)
df_20231231 = preprocess_data(df_20231231)
df_20240630 = preprocess_data(df_20240630)
df_20241231 = preprocess_data(df_20241231)
df_20250630 = preprocess_data(df_20250630)
df_20251231 = preprocess_data(df_20251231)

# 각 데이터프레임들의 결측치 확인
print(check_missing_values(df_20230831, "2023-08-31")) # 2021년 7월부터 2023년 8월까지의 데이터는 누적되어 업데이트
print(check_missing_values(df_20231231, "2023-12-31"))
print(check_missing_values(df_20240630, "2024-06-30"))
print(check_missing_values(df_20241231, "2024-12-31"))
print(check_missing_values(df_20250630, "2025-06-30"))
print(check_missing_values(df_20251231, "2025-12-31"))

2023-08-31 결측치 개수:
신고일    0
구정보    0
주소     0
유형     0
조치일    0
신고월    0
dtype: int64
None
2023-12-31 결측치 개수:
신고일    0
구정보    0
주소     0
유형     0
조치일    0
신고월    0
dtype: int64
None
2024-06-30 결측치 개수:
신고일    0
구정보    0
주소     0
유형     0
조치일    0
신고월    0
dtype: int64
None
2024-12-31 결측치 개수:
신고일    0
구정보    0
주소     0
유형     0
조치일    0
신고월    0
dtype: int64
None
2025-06-30 결측치 개수:
신고일    0
구정보    0
주소     0
유형     0
조치일    0
신고월    0
dtype: int64
None
2025-12-31 결측치 개수:
신고일    0
구정보    0
주소     0
유형     0
조치일    0
신고월    0
dtype: int64
None

### 결측치, 데이터타입, 신고월 파생변수 추가가 성공적으로 완료
### 해당 데이터프레임들을 하나로 병합합니다.

In [ ]:
# 전처리된 데이터프레임들을 하나로 병합
df_merged = pd.concat(
    [df_20230831, df_20231231, 
     df_20240630, df_20241231, 
     df_20250630, df_20251231], 
     ignore_index=True)

# 병합된 데이터프레임 정보 출력
print(df_merged.info())
display(df_merged.head(3))
display(df_merged.tail(3))

<class 'pandas.DataFrame'>
RangeIndex: 300792 entries, 0 to 300791
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   신고일     300792 non-null  datetime64[us]
 1   구정보     300792 non-null  str
 2   주소      300792 non-null  str
 3   유형      300792 non-null  str
 4   조치일     300792 non-null  datetime64[us]
 5   신고월     300792 non-null  period[M]
dtypes: datetime64[us](2), period[M](1), str(3)
memory usage: 13.8 MB
None

,신고일,구정보,주소,유형,조치일,신고월
0,2021-07-15,영등포구,서울특별시 영등포구 여의도동 84-10,보도와 차도가 구분된 도로의 차도,2021-07-15,2021-07
1,2021-07-15,영등포구,서울특별시 영등포구 영등포동1가 97-4,보도 중앙,2021-07-15,2021-07
2,2021-07-15,동작구,서울특별시 동작구 노량진동 231-2,보도와 차도가 구분된 도로의 차도,2021-07-15,2021-07

,신고일,구정보,주소,유형,조치일,신고월
300789,2025-12-31,강서구,서울특별시 강서구 화곡동 1146,보도와 차도가 구분된 도로의 차도,2025-12-31,2025-12
300790,2025-12-31,강서구,서울특별시 강서구 가양동 1484,보호구역(어린이·노인·장애인),2025-12-31,2025-12
300791,2025-12-31,서대문구,서울특별시 서대문구 남가좌동 293-3,지하철역 전면(5m이내),2025-12-31,2025-12

### 병합된 결과 데이터프레임 파일 저장(CSV) 및 정상적으로 저장되었는지 확인

In [87]:
# 병합된 데이터프레임 파일 저장
# 저장 시, 인코딩은 'utf-8-sig'로 지정
df_merged.to_csv('서울특별시_전동킥보드_견인_현황_202107~202512.csv', index=False, encoding='utf-8-sig')

In [ ]:
# 저장한 파일 정상적으로 저장되었는지 확인
# parse_dates 옵션을 사용하여 '신고일'과 '조치일'을 datetime 형식으로 읽어오기
df_merged_check = pd.read_csv('서울특별시_전동킥보드_견인_현황_202107~202512.csv', 
                              encoding='utf-8-sig', parse_dates=['신고일', '조치일'])
print(df_merged_check.info())
display(df_merged_check.head(3))
display(df_merged_check.tail(3))

<class 'pandas.DataFrame'>
RangeIndex: 300792 entries, 0 to 300791
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   신고일     300792 non-null  datetime64[us]
 1   구정보     300792 non-null  str
 2   주소      300792 non-null  str
 3   유형      300792 non-null  str
 4   조치일     300792 non-null  datetime64[us]
 5   신고월     300792 non-null  str
dtypes: datetime64[us](2), str(4)
memory usage: 13.8 MB
None

,신고일,구정보,주소,유형,조치일,신고월
0,2021-07-15,영등포구,서울특별시 영등포구 여의도동 84-10,보도와 차도가 구분된 도로의 차도,2021-07-15,2021-07
1,2021-07-15,영등포구,서울특별시 영등포구 영등포동1가 97-4,보도 중앙,2021-07-15,2021-07
2,2021-07-15,동작구,서울특별시 동작구 노량진동 231-2,보도와 차도가 구분된 도로의 차도,2021-07-15,2021-07

,신고일,구정보,주소,유형,조치일,신고월
300789,2025-12-31,강서구,서울특별시 강서구 화곡동 1146,보도와 차도가 구분된 도로의 차도,2025-12-31,2025-12
300790,2025-12-31,강서구,서울특별시 강서구 가양동 1484,보호구역(어린이·노인·장애인),2025-12-31,2025-12
300791,2025-12-31,서대문구,서울특별시 서대문구 남가좌동 293-3,지하철역 전면(5m이내),2025-12-31,2025-12