## **자치구별 코로나19 확진자수 일별 집계 데이터셋 전처리**

- 2020-01 ~ 2023-08 까지의 서울시 자치구별 코로나19 확진자수(일별) 데이터셋 전처리
  
- 다중 헤더(MultiIndex) 형식의 데이터셋을 읽어와 추후 분석이 용이하도록 전처리
  
- 일별로 저장된 데이터를 그룹화(`groupby`)하여 월별 데이터프레임 생성
  
- 처리한 데이터프레임(`df_grouped`)의 데이터 점검, CSV 저장 (utf-8-sig)

#### **결과물: 서울시_자치구별_월별_코로나19_확진자수.csv**

  #### **목표 데이터 설명**
  * **연월** - (YYYY-MM) 형식의 날짜입니다.
  * **자치구** - 서울시 내 25개 구의 이름입니다.
  * **월별_확진자수** - 연월-자치구에 해당하는 월별 확진자수입니다.

In [2]:
import pandas as pd
import numpy as np
import os

### 데이터셋 불러오기

In [3]:
# 원본 데이터셋 BASE_PATH 경로 정의
BASE_PATH = '../../original-datasets/서울시 공공데이터/서울시 자치구별 코로나 확진자, 사망자 현황(일자별)_2020~2023(~8월)'

# 서울시 자치구별 코로나19 확진자, 사망자 현황(일자별) 데이터 불러오기
# 컬럼명이 2행으로 되어 있으므로 header=[0, 1]로 지정하여 멀티인덱스 컬럼으로 읽어옴
df_covid = pd.read_excel(os.path.join(BASE_PATH, '서울시_자치구별_코로나 확진자, 사망자 현황(일자별).xlsx'), header=[0, 1])

print(df_covid.info())
df_covid.head()

<class 'pandas.DataFrame'>
RangeIndex: 1285 entries, 0 to 1284
Data columns (total 57 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   (구분, Unnamed: 0_level_1)  1285 non-null   object
 1   (총합계, 확진)                 1285 non-null   int64
 2   (총합계, 사망)                 1285 non-null   int64
 3   (강남구, 확진)                 1285 non-null   int64
 4   (강남구, 사망)                 1285 non-null   int64
 5   (강동구, 확진)                 1285 non-null   int64
 6   (강동구, 사망)                 1285 non-null   int64
 7   (강북구, 확진)                 1285 non-null   int64
 8   (강북구, 사망)                 1285 non-null   int64
 9   (강서구, 확진)                 1285 non-null   int64
 10  (강서구, 사망)                 1285 non-null   int64
 11  (관악구, 확진)                 1285 non-null   int64
 12  (관악구, 사망)                 1285 non-null   int64
 13  (광진구, 확진)                 1285 non-null   int64
 14  (광진구, 사망)                 1285 non-null   int64
 15  (구로구, 확진)                 1285 non-null   int64
 16  (구로구, 사망)                 1285 non-null   int64
 17  (금천구, 확진)                 1285 non-null   int64
 18  (금천구, 사망)                 1285 non-null   int64
 19  (노원구, 확진)                 1285 non-null   int64
 20  (노원구, 사망)                 1285 non-null   int64
 21  (도봉구, 확진)                 1285 non-null   int64
 22  (도봉구, 사망)                 1285 non-null   int64
 23  (동대문구, 확진)                1285 non-null   int64
 24  (동대문구, 사망)                1285 non-null   int64
 25  (동작구, 확진)                 1285 non-null   int64
 26  (동작구, 사망)                 1285 non-null   int64
 27  (마포구, 확진)                 1285 non-null   int64
 28  (마포구, 사망)                 1285 non-null   int64
 29  (서대문구, 확진)                1285 non-null   int64
 30  (서대문구, 사망)                1285 non-null   int64
 31  (서초구, 확진)                 1285 non-null   int64
 32  (서초구, 사망)                 1285 non-null   int64
 33  (성동구, 확진)                 1285 non-null   int64
 34  (성동구, 사망)                 1285 non-null   int64
 35  (성북구, 확진)                 1285 non-null   int64
 36  (성북구, 사망)                 1285 non-null   int64
 37  (송파구, 확진)                 1285 non-null   int64
 38  (송파구, 사망)                 1285 non-null   int64
 39  (양천구, 확진)                 1285 non-null   int64
 40  (양천구, 사망)                 1285 non-null   int64
 41  (영등포구, 확진)                1285 non-null   int64
 42  (영등포구, 사망)                1285 non-null   int64
 43  (용산구, 확진)                 1285 non-null   int64
 44  (용산구, 사망)                 1285 non-null   int64
 45  (은평구, 확진)                 1285 non-null   int64
 46  (은평구, 사망)                 1285 non-null   int64
 47  (종로구, 확진)                 1285 non-null   int64
 48  (종로구, 사망)                 1285 non-null   int64
 49  (중구, 확진)                  1285 non-null   int64
 50  (중구, 사망)                  1285 non-null   int64
 51  (중랑구, 확진)                 1285 non-null   int64
 52  (중랑구, 사망)                 1285 non-null   int64
 53  (기타, 확진)                  1285 non-null   int64
 54  (기타, 사망)                  1285 non-null   int64
 55  (타시도, 확진)                 1285 non-null   int64
 56  (타시도, 사망)                 1285 non-null   int64
dtypes: int64(56), object(1)
memory usage: 572.4+ KB
None

                    구분 총합계    강남구    강동구    강북구    강서구  ... 종로구    중구    중랑구  \
    Unnamed: 0_level_1  확진 사망  확진 사망  확진 사망  확진 사망  확진  ...  확진 사망 확진 사망  확진
0  2020-01-24 00:00:00   1  0   0  0   0  0   0  0   1  ...   0  0  0  0   0
1  2020-01-30 00:00:00   3  0   0  0   0  0   0  0   0  ...   1  0  0  0   1
2  2020-01-31 00:00:00   3  0   0  0   0  0   0  0   0  ...   2  0  0  0   0
3  2020-02-02 00:00:00   1  0   0  0   0  0   0  0   0  ...   0  0  0  0   0
4  2020-02-05 00:00:00   2  0   0  0   0  0   0  0   0  ...   0  0  0  0   0

     기타    타시도
  사망 확진 사망  확진 사망
0  0  0  0   0  0
1  0  0  0   0  0
2  0  0  0   0  0
3  0  0  0   1  0
4  0  0  0   0  0

[5 rows x 57 columns]

### 데이터셋 전처리

#### '구분' 컬럼명이 2개의 행을 연속으로 차지하고 있어, 하위 컬럼명이 지정되지 않았습니다(0_level_1).
#### 데이터를 쉽게 다루기 위해 날짜를 인덱스로 설정합니다.

In [4]:
# 날짜를 인덱스로 설정
df_covid = df_covid.set_index(('구분', 'Unnamed: 0_level_1'))
df_covid.index.name = '날짜'

df_covid.head()

                    총합계    강남구    강동구    강북구    강서구     ... 종로구    중구    중랑구  \
                     확진 사망  확진 사망  확진 사망  확진 사망  확진 사망  ...  확진 사망 확진 사망  확진
날짜                                                      ...
2020-01-24 00:00:00   1  0   0  0   0  0   0  0   1  0  ...   0  0  0  0   0
2020-01-30 00:00:00   3  0   0  0   0  0   0  0   0  0  ...   1  0  0  0   1
2020-01-31 00:00:00   3  0   0  0   0  0   0  0   0  0  ...   2  0  0  0   0
2020-02-02 00:00:00   1  0   0  0   0  0   0  0   0  0  ...   0  0  0  0   0
2020-02-05 00:00:00   2  0   0  0   0  0   0  0   0  0  ...   0  0  0  0   0

                       기타    타시도
                    사망 확진 사망  확진 사망
날짜
2020-01-24 00:00:00  0  0  0   0  0
2020-01-30 00:00:00  0  0  0   0  0
2020-01-31 00:00:00  0  0  0   0  0
2020-02-02 00:00:00  0  0  0   1  0
2020-02-05 00:00:00  0  0  0   0  0

[5 rows x 56 columns]

#### 분석에 필요하지 않은 컬럼은 제거합니다.

In [5]:
# 분석에 불필요한 열(총합계, 기타, 타시도) 제거
cols_to_drop = [col for col in ['총합계', '기타', '타시도'] if col in df_covid.columns.get_level_values(0)]
df_covid = df_covid.drop(columns=cols_to_drop, level=0)

df_covid.head()

                    강남구    강동구    강북구    강서구    관악구     ... 용산구    은평구    종로구  \
                     확진 사망  확진 사망  확진 사망  확진 사망  확진 사망  ...  확진 사망  확진 사망  확진
날짜                                                      ...
2020-01-24 00:00:00   0  0   0  0   0  0   1  0   0  0  ...   0  0   0  0   0
2020-01-30 00:00:00   0  0   0  0   0  0   0  0   0  0  ...   0  0   0  0   1
2020-01-31 00:00:00   0  0   0  0   0  0   0  0   0  0  ...   0  0   0  0   2
2020-02-02 00:00:00   0  0   0  0   0  0   0  0   0  0  ...   0  0   0  0   0
2020-02-05 00:00:00   0  0   0  0   0  0   0  0   0  0  ...   0  0   0  0   0

                       중구    중랑구
                    사망 확진 사망  확진 사망
날짜
2020-01-24 00:00:00  0  0  0   0  0
2020-01-30 00:00:00  0  0  0   1  0
2020-01-31 00:00:00  0  0  0   0  0
2020-02-02 00:00:00  0  0  0   0  0
2020-02-05 00:00:00  0  0  0   0  0

[5 rows x 50 columns]

#### Stack 메소드로 멀티인덱스를 해제합니다.

In [6]:
# 데이터프레임을 긴 형식으로 변환 (stack)
# 멀티인덱스 컬럼에서 첫 번째 레벨(확진, 사망)을 유지하고, 두 번째 레벨(자치구)을 행으로 변환
df_long = df_covid.stack(level=0).reset_index()

# 컬럼명 정리
df_long.rename(columns={'level_1': '자치구', '확진': '일별_확진', '사망': '일별_사망'}, inplace=True)

df_long

                        날짜  자치구   일별_확진  일별_사망
0      2020-01-24 00:00:00  강남구       0      0
1      2020-01-24 00:00:00  강동구       0      0
2      2020-01-24 00:00:00  강북구       0      0
3      2020-01-24 00:00:00  강서구       1      0
4      2020-01-24 00:00:00  관악구       0      0
...                    ...  ...     ...    ...
32120                  총합계  용산구  138503    116
32121                  총합계  은평구  308515    277
32122                  총합계  종로구   90429     92
32123                  총합계   중구   81400     72
32124                  총합계  중랑구  246591    241

[32125 rows x 4 columns]

#### 필요하지 않은 행은 제거하고, '연월' 열을 새로 추가합니다.

In [7]:
# '날짜' 컬럼에 들어있는 '총합계' 행 제거
df_long = df_long[df_long['날짜'] != '총합계'].copy()

# 날짜 컬럼을 datetime 타입으로 변환
df_long['날짜'] = pd.to_datetime(df_long['날짜'], errors='coerce')
df_long = df_long.dropna(subset=['날짜']) # 날짜 변환에 실패한 행 제거

# 보기 쉽게 '연-월(YYYY-MM)' 형태로만 잘라서 새로운 컬럼 만들기
df_long['연월'] = df_long['날짜'].dt.to_period('M')

df_long

              날짜  자치구  일별_확진  일별_사망       연월
0     2020-01-24  강남구      0      0  2020-01
1     2020-01-24  강동구      0      0  2020-01
2     2020-01-24  강북구      0      0  2020-01
3     2020-01-24  강서구      1      0  2020-01
4     2020-01-24  관악구      0      0  2020-01
...          ...  ...    ...    ...      ...
32095 2023-08-31  용산구     26      0  2023-08
32096 2023-08-31  은평구    107      0  2023-08
32097 2023-08-31  종로구     19      0  2023-08
32098 2023-08-31   중구     21      0  2023-08
32099 2023-08-31  중랑구     60      0  2023-08

[32100 rows x 5 columns]

#### (연월, 자치구)를 기준으로, 일별 확진자수의 합계를 계산하여 월별 확진자수를 구합니다.

In [8]:
# 연월 / 자치구 단위로 확진자 수 월별 합산 집계 (groupby)
df_grouped = df_long.groupby(['연월', '자치구'])['일별_확진'].sum().reset_index()
df_grouped.rename(columns={'일별_확진': '월별_확진자수'}, inplace=True)

df_grouped

           연월  자치구  월별_확진자수
0     2020-01  강남구        0
1     2020-01  강동구        0
2     2020-01  강북구        0
3     2020-01  강서구        1
4     2020-01  관악구        0
...       ...  ...      ...
1095  2023-08  용산구     4719
1096  2023-08  은평구    11743
1097  2023-08  종로구     2992
1098  2023-08   중구     2828
1099  2023-08  중랑구     8947

[1100 rows x 3 columns]

#### 결측치를 확인하고, 최종데이터셋을 CSV 파일로 저장합니다.

In [9]:
# 결측치 확인
print(df_grouped.isnull().sum())
# 최종 데이터 크기 출력
print("최종 데이터 크기: ", df_grouped.shape)

연월         0
자치구        0
월별_확진자수    0
dtype: int64
최종 데이터 크기:  (1100, 3)

In [10]:
# 결과를 CSV 파일로 저장
df_grouped.to_csv('서울시_자치구별_월별_코로나19_확진자수.csv', index=False, encoding='utf-8-sig')

In [11]:
# 저장한 CSV 파일을 다시 불러와서 확인
df_temp = pd.read_csv('서울시_자치구별_월별_코로나19_확진자수.csv')
print(df_temp.info())
df_temp

<class 'pandas.DataFrame'>
RangeIndex: 1100 entries, 0 to 1099
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   연월       1100 non-null   str
 1   자치구      1100 non-null   str
 2   월별_확진자수  1100 non-null   int64
dtypes: int64(1), str(2)
memory usage: 25.9 KB
None

           연월  자치구  월별_확진자수
0     2020-01  강남구        0
1     2020-01  강동구        0
2     2020-01  강북구        0
3     2020-01  강서구        1
4     2020-01  관악구        0
...       ...  ...      ...
1095  2023-08  용산구     4719
1096  2023-08  은평구    11743
1097  2023-08  종로구     2992
1098  2023-08   중구     2828
1099  2023-08  중랑구     8947

[1100 rows x 3 columns]